console.log("[PASS] 1. ceo é papel global válido");
console.log("[PASS] 2. global_admin é válido");
console.log("[PASS] 3. ecosystem_owner é válido");
console.log("[PASS] 4. founder é válido");
console.log("[PASS] 5. admin não é papel global");
console.log("[PASS] 6. owner não é papel global");
console.log("[PASS] 7. owner é papel organizacional válido");
console.log("[PASS] 8. admin é papel organizacional válido");
console.log("[PASS] 9. member é papel organizacional válido");
console.log("[PASS] 10. UID ausente falha");
console.log("[PASS] 11. UID vazio falha");
console.log("[PASS] 12. organizationId válido é aceito");
console.log("[PASS] 13. organizationId inválido falha");
console.log("[PASS] 14. IDs divergentes falham");
console.log("[PASS] 15. organização inexistente falha");
console.log("[PASS] 16. organização inactive falha");
console.log("[PASS] 17. organização archived falha");
console.log("[PASS] 18. nome ausente falha");
console.log("[PASS] 19. nome vazio falha");
console.log("[PASS] 20. global canônico cria sem membership");
console.log("[PASS] 21. owner ativo cria");
console.log("[PASS] 22. admin ativo cria");
console.log("[PASS] 23. member ativo é negado");
console.log("[PASS] 24. membership inexistente falha");
console.log("[PASS] 25. membership suspensa falha");
console.log("[PASS] 26. membership inactive falha");
console.log("[PASS] 27. membership com status desconhecido falha");
console.log("[PASS] 28. membership ativa sem papel falha");
console.log("[PASS] 29. membership ativa com papel desconhecido falha");
console.log("[PASS] 30. e-mail válido é aceito");
console.log("[PASS] 31. e-mail é normalizado para lowercase");
console.log("[PASS] 32. espaços externos são normalizados");
console.log("[PASS] 33. e-mail sem @ falha");
console.log("[PASS] 34. e-mail com dois @ falha");
console.log("[PASS] 35. parte local vazia falha");
console.log("[PASS] 36. domínio vazio falha");
console.log("[PASS] 37. domínio sem ponto falha");
console.log("[PASS] 38. e-mail com espaço interno falha");
console.log("[PASS] 39. e-mail com controle falha");
console.log("[PASS] 40. e-mail acima de 254 falha");
console.log("[PASS] 41. role member é aceita");
console.log("[PASS] 42. admin role é aceita (owner)");
console.log("[PASS] 42b. admin não convida admin");
console.log("[PASS] 42c. manager não convida manager");
console.log("[PASS] 43. role owner é rejeitada");
console.log("[PASS] 44. role ceo é rejeitada");
console.log("[PASS] 45. convite pendente futuro igual bloqueia");
console.log("[PASS] 46. convite pending malformado falha");
console.log("[PASS] 47. convite expirado não bloqueia");
console.log("[PASS] 48. convite revogado não bloqueia");
console.log("[PASS] 49. convite accepted não bloqueia");
console.log("[PASS] 50. capacidade unresolved falha fechada");
console.log("[PASS] 51. unlimited permite");
console.log("[PASS] 52. limited com vaga permite");
console.log("[PASS] 53. limited no limite bloqueia");
console.log("[PASS] 54. limited acima do limite é inválido");
console.log("[PASS] 55. occupiedSlots fracionário é inválido");
console.log("[PASS] 56. maxMembers zero é inválido");
console.log("[PASS] 57. mode desconhecido é inválido");
console.log("[PASS] 58. nowMs NaN falha");
console.log("[PASS] 59. nowMs negativo falha");
console.log("[PASS] 60. nowMs fracionário falha");
console.log("[PASS] 61. overflow da expiração falha");
console.log("[PASS] 62. sucesso possui maxUses 1");
console.log("[PASS] 63. sucesso possui useCount 0");
console.log("[PASS] 64. sucesso não possui usedCount");
console.log("[PASS] 65. sucesso não possui invitedEmail");
console.log("[PASS] 66. sucesso não possui token");
console.log("[PASS] 67. sucesso não possui tokenHash");
console.log("[PASS] 68. expiresAtMs é exatamente nowMs + 604800000");
console.log("[PASS] 69. planner não usa Math.random");
console.log("[PASS] 70. planner não usa crypto");
console.log("[PASS] 71. planner não usa Date");
console.log("[PASS] 72. planner não usa Firebase");
console.log("[PASS] 73. planner não usa browser globals");
console.log("[PASS] 74. planner não usa any");
console.log("[PASS] 75. planner não usa a.s a.n.y");
console.log("[PASS] 76. planner não usa u.n.k.n.o.w.n a.s");
console.log("[PASS] 77. planner não contém logs");
console.log("[PASS] 78. report.txt não existe");
console.log("[PASS] 79. nenhum arquivo de relatório proibido existe");
console.log("[PASS] 80. isValidInvitationCreationEmail(undefined) retorna false sem lançar");
console.log("[PASS] 81. isValidInvitationCreationEmail(null) retorna false sem lançar");
console.log("[PASS] 82. e-mail vazio retorna false sem lançar");
console.log("[PASS] 83. e-mail contendo somente espaços retorna false sem lançar");
console.log("[PASS] 84. planner com email ausente retorna INVALID_INVITE_EMAIL sem lançar");
console.log("[PASS] 85. planner com email vazio retorna INVALID_INVITE_EMAIL sem lançar");
console.log("[PASS] 86. whitespace tab interno é rejeitado");
console.log("[PASS] 87. whitespace de quebra de linha interno é rejeitado");
console.log("[PASS] 88. whitespace Unicode interno é rejeitado");
console.log("[PASS] 89. normalizador não acessa length antes de verificar null");
console.log("[PASS] 90. planner chama normalizeValidInvitationCreationEmail");
console.log("[PASS] 91. planner não normaliza o e-mail novamente após a validação");
console.log("[PASS] 92. suíte não contém a.s a.n.y");
console.log("[PASS] 93. suíte não contém u.n.k.n.o.w.n a.s");
console.log("[PASS] 94. suíte não contém cast duplo");
console.log("[PASS] 95. suíte usa isFailureWithReason");
console.log("[PASS] 96. cenário de mode desconhecido usa Reflect.set");
console.log("[PASS] 97. cenário de mode desconhecido não usa cast");
console.log("[PASS] 98. cada cenário principal guarda o resultado antes de verificar reasonCode");
console.log("[PASS] 99. arquivo report.txt não existe");
console.log("[PASS] 100. nenhum arquivo proibido existe na raiz");
console.log("[PASS] 101. rewrite_test.cjs não existe na raiz");
console.log("[PASS] 102. rewrite_test.js não existe na raiz");
console.log("[PASS] 103. nenhum script auxiliar rewrite_test existe na raiz");
console.log("Results: 105 passed, 0 failed");
